site_name: grm.labs

theme:
  language: es
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.footer
  font:
    text: Noto Sans JP
    code: Noto Sans Mono
  palette:
    scheme: grmlabs

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gruizmudarra
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/gruizmudarra
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/grm.labs

extra_css:
  - stylesheets/extra.css

plugins:
  - blog:
      enabled: true
      blog_dir: blog
      blog_toc: false
      post_dir: "{blog}/posts"
      post_url_max_categories: 1
      post_slugify_separator: "-"
      post_excerpt_max_authors: 1
      post_excerpt_max_categories: 5
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      post_readtime_words_per_minute: 265
      archive: true
      archive_name: Archive
      archive_toc: false
      categories: true
      categories_name: Categories
      categories_slugify_separator: "-"
      categories_toc: false
      pagination: true
      pagination_per_page: 10
      pagination_keep_content: false
      authors: true
      authors_file: "{blog}/.authors.yml"
      draft: false
      draft_on_serve: true
      draft_if_future_date: false